global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: backends
    static_configs:
      - targets: ['46.101.109.57:9091', '46.101.220.48:9091', '207.154.241.16:9091']

  - job_name: balancer
    static_configs:
      - targets: ['localhost:9091']
